config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root 'static_pages#home'
  
  match 'microposts',       to: 'microposts#update',       via: 'patch'
  match '/aureline',    to: 'static_pages#aureline',    via: 'get'
  match '/charles',    to: 'static_pages#charles',    via: 'get'
  match '/amaury',    to: 'static_pages#amaury',    via: 'get'
  match '/other',    to: 'static_pages#other',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',  via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/views/layouts/_footer.html.erb
<footer id="footer">


  <div class="container">
    <div class="row">
      <div class="col-xs-6 col-sm-2 col-md-3">
        <ol>
          <li class="header">
            Our products 
          </li>
          <% if signed_in? %>
          <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          <% else %>
          <li><%= link_to "Sign up",   signup_path %></li>
          <li><%= link_to "Sign in",   signin_path %></li>
          <% end %>
          <li><%= link_to "Apps",   "#" %></li>
        </ol>
      </div>
      
      <div class="col-xs-6 col-sm-2 col-md-3">
        <ol>
          <li class="header">
            Our team 
          </li>
          <li><%= link_to "Charles", charles_path %></li>
          <li><%= link_to "Lily",   aureline_path %></li>
          <li><%= link_to "Amaury",   amaury_path %></li>
        </ol>
      </div>
      
      
      <div class="col-xs-6 col-sm-2 col-md-3">
        <ol>
          <li class="header">
            Support
          </li>
          <li>
            <%= link_to "Help & Privacy",   help_path %>
          </li>
          <li>
            <%= link_to "About",   about_path %>
          </li>
          <li>
            <%= link_to "Contact",   contact_path %>
          </li>
        </ol>
      </div>


      <div class="col-xs-6 col-sm-2 col-md-3">
        <ol>
          <li class="header">
            Follow us
          </li>
          <li>
            <%= link_to image_tag("icon-facebook.png", alt: "Facebook"),   "https://www.facebook.com/WhatsNapp", target: "_blank" %>
          </li>
        </ol>
      </div>
      <div class="col-xs-0 col-sm-2 col-md-1">
      </div>

    </div>
  </div>
  <div class="copyrights">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 cp-label text-left">
          Copyright &copy; 2014 WhatsNapp
          <div style="width:130px;margin-left:auto;margin-right:auto;position:relative;">
            <a href="#" id="to-home"><span class="th-border"></span><span class="th-solid"></span><i></i><span class="th-label hidden-xs">Back to Top</span></a>
          </div>
        </div>
      </div>
    </div>
  </div>

</footer>

app/views/layouts/_header.html.erb
  <header id="header">
    <div class="container">
      <% if signed_in? %> 
      <nav class="navbar navbar_logged_in navbar-fixed-top" role="navigation">
        <%else%>
        <nav class="navbar navbar-fixed-top" role="navigation">
          <%end%>
          <div class="col-xs-1 col-sm-1 col-md-1">
          </div>

          <% if signed_in? %> 
          <%= link_to image_tag("yellow-maple-leaf-logo-small.png", alt: "logo"), root_path, id: "logo" %>
          <%= link_to "WhatsNapp//", root_path, id: "logo-text" %>  
          <%= link_to current_user.name, current_user, class: "usernametitle" %>  
          <ul class= "nav pull-right" id="logged_in_menu">
            <li><%= link_to "News", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <li><%= link_to "Users", users_path %></li>
            <li  class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              </ul>
            </li>
          </ul>
          <% else %>
          
          <%= link_to image_tag("blue-maple-leaf-logo-small.png", alt: "logo"), root_path, id: "logo" %>
          <%= link_to "WhatsNapp", root_path, id: "logo-text" %>  
          <ul class="nav" id= "slogan">
            <li> - Conversations with shared notes</li>
          </ul>    
          <ul class= "nav pull-right">
            <li><%= form_for(:session, url: sessions_path, html: { class: "form-inline" , :id => 'sign-in-form'}) do |f| %></li>
            <li class="input-group"><%= f.text_field :email, class: "span3", id:"input_to_be_loaded", placeholder: "Email address"%></li>
            <li class="input-group"><%= f.password_field :password, class: "span3", placeholder: "Password"%></li>
            <li class="input-group" style="margin-top: 6px;"><%= f.submit "Sign in", class: "btn btn-signin" , id: "sign-in-button" %> </li>
            <% end %>
          </ul>
          <% end %>
        </nav>

        <aside id="sidebar" role="sidebar-primary" class="sidebar hidden-desktop">
          <div class="sidebar-inner">
            <ul>
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Help", help_path %></li>
              <% if signed_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
              <% end %> 
            </ul>
          </div>
        </aside>

      </div>
      
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>

  <meta charset="utf-8" />
  <title>WhatsNapp - Conversations with notes on the side</title>
  <meta property="og:title" content="WhatsNapp - Conversations with notes on the side"/>
  <meta property="og:site_name" content="WhatsNapp"/>
  <meta property="og:type" content="website"/>
  <link href="//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&subset=latin,latin-ext" rel="stylesheet" type="text/css"/>
  

  
  <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
  <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">


  <%= javascript_include_tag "show" %>
  <%= stylesheet_link_tag "application", media: "all",
  "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>

<script TYPE="text/javascript">
$(function() {
    // there's the conversation-messages and the notes

    var $conversation = $( "#conversation-messages" ),
      $notes = $( "#notes" );
      $("li", $conversation).css( 'cursor', 'pointer' );
    // let the conversation-messages items be draggable
    $( "li", $conversation ).draggable({
      cancel: "a.ui-icon", // clicking an icon won't initiate dragging
      revert: "invalid", // when not dropped, the item will revert back to its initial position
      containment: "document",
      helper: "clone",
      cursor: "move"
    });
 
    // let the notes be droppable, accepting the conversation-messages items
    $notes.droppable({
      accept: "#conversation-messages > li",
      activeClass: "ui-state-highlight",
      drop: function( event, ui ) {
        deleteImage( ui.draggable );
      }
    });

</script>

  <SCRIPT TYPE="text/javascript">
    function submitenter(myfield,e)
    {
      var keycode;
      if (window.event) keycode = window.event.keyCode;
      else if (e) keycode = e.which;
      else return true;

      if (keycode == 13)
      {
       myfield.form.submit();
       return false;
     }
     else
       return true;
   }
  </SCRIPT>

<%= javascript_include_tag :defaults %>
</head>

<body>
  <%= render 'layouts/header' %>
  
  <% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>



  <%= yield %>
  <%= render 'layouts/footer' %>
  <% if false %>
  <%= debug(params) if Rails.env.development? %>
  <%end%>



  <script language="javascript" type="text/javascript">
    document.getElementById("input_to_be_loaded").focus();
  </script>


</body>
</html>